// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: autodrive.proto

package com.autodrive.message;

public final class Autodrive {
  private Autodrive() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autodrive.message.LocationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code com.autodrive.message.LocationMessage}
   */
  public static final class LocationMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.autodrive.message.LocationMessage)
      LocationMessageOrBuilder {
    // Use LocationMessage.newBuilder() to construct.
    private LocationMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LocationMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LocationMessage defaultInstance;
    public static LocationMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LocationMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LocationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_LocationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_LocationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autodrive.message.Autodrive.LocationMessage.class, com.autodrive.message.Autodrive.LocationMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<LocationMessage> PARSER =
        new com.google.protobuf.AbstractParser<LocationMessage>() {
      public LocationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LocationMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LocationMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private void initFields() {
      latitude_ = 0D;
      longitude_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autodrive.message.Autodrive.LocationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.autodrive.message.Autodrive.LocationMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.autodrive.message.LocationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autodrive.message.LocationMessage)
        com.autodrive.message.Autodrive.LocationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_LocationMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_LocationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autodrive.message.Autodrive.LocationMessage.class, com.autodrive.message.Autodrive.LocationMessage.Builder.class);
      }

      // Construct using com.autodrive.message.Autodrive.LocationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_LocationMessage_descriptor;
      }

      public com.autodrive.message.Autodrive.LocationMessage getDefaultInstanceForType() {
        return com.autodrive.message.Autodrive.LocationMessage.getDefaultInstance();
      }

      public com.autodrive.message.Autodrive.LocationMessage build() {
        com.autodrive.message.Autodrive.LocationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autodrive.message.Autodrive.LocationMessage buildPartial() {
        com.autodrive.message.Autodrive.LocationMessage result = new com.autodrive.message.Autodrive.LocationMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autodrive.message.Autodrive.LocationMessage) {
          return mergeFrom((com.autodrive.message.Autodrive.LocationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autodrive.message.Autodrive.LocationMessage other) {
        if (other == com.autodrive.message.Autodrive.LocationMessage.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autodrive.message.Autodrive.LocationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autodrive.message.Autodrive.LocationMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.autodrive.message.LocationMessage)
    }

    static {
      defaultInstance = new LocationMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.autodrive.message.LocationMessage)
  }

  public interface SegmentListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.autodrive.message.SegmentList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    java.util.List<com.autodrive.message.Autodrive.LocationMessage> 
        getLocationsList();
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    com.autodrive.message.Autodrive.LocationMessage getLocations(int index);
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    int getLocationsCount();
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    java.util.List<? extends com.autodrive.message.Autodrive.LocationMessageOrBuilder> 
        getLocationsOrBuilderList();
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    com.autodrive.message.Autodrive.LocationMessageOrBuilder getLocationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.autodrive.message.SegmentList}
   */
  public static final class SegmentList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.autodrive.message.SegmentList)
      SegmentListOrBuilder {
    // Use SegmentList.newBuilder() to construct.
    private SegmentList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SegmentList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SegmentList defaultInstance;
    public static SegmentList getDefaultInstance() {
      return defaultInstance;
    }

    public SegmentList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SegmentList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                locations_ = new java.util.ArrayList<com.autodrive.message.Autodrive.LocationMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              locations_.add(input.readMessage(com.autodrive.message.Autodrive.LocationMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          locations_ = java.util.Collections.unmodifiableList(locations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_SegmentList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_SegmentList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.autodrive.message.Autodrive.SegmentList.class, com.autodrive.message.Autodrive.SegmentList.Builder.class);
    }

    public static com.google.protobuf.Parser<SegmentList> PARSER =
        new com.google.protobuf.AbstractParser<SegmentList>() {
      public SegmentList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SegmentList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SegmentList> getParserForType() {
      return PARSER;
    }

    public static final int LOCATIONS_FIELD_NUMBER = 1;
    private java.util.List<com.autodrive.message.Autodrive.LocationMessage> locations_;
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    public java.util.List<com.autodrive.message.Autodrive.LocationMessage> getLocationsList() {
      return locations_;
    }
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    public java.util.List<? extends com.autodrive.message.Autodrive.LocationMessageOrBuilder> 
        getLocationsOrBuilderList() {
      return locations_;
    }
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    public int getLocationsCount() {
      return locations_.size();
    }
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    public com.autodrive.message.Autodrive.LocationMessage getLocations(int index) {
      return locations_.get(index);
    }
    /**
     * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
     */
    public com.autodrive.message.Autodrive.LocationMessageOrBuilder getLocationsOrBuilder(
        int index) {
      return locations_.get(index);
    }

    private void initFields() {
      locations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getLocationsCount(); i++) {
        if (!getLocations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < locations_.size(); i++) {
        output.writeMessage(1, locations_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < locations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, locations_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.autodrive.message.Autodrive.SegmentList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.autodrive.message.Autodrive.SegmentList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.autodrive.message.Autodrive.SegmentList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.autodrive.message.SegmentList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.autodrive.message.SegmentList)
        com.autodrive.message.Autodrive.SegmentListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_SegmentList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_SegmentList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.autodrive.message.Autodrive.SegmentList.class, com.autodrive.message.Autodrive.SegmentList.Builder.class);
      }

      // Construct using com.autodrive.message.Autodrive.SegmentList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLocationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.autodrive.message.Autodrive.internal_static_com_autodrive_message_SegmentList_descriptor;
      }

      public com.autodrive.message.Autodrive.SegmentList getDefaultInstanceForType() {
        return com.autodrive.message.Autodrive.SegmentList.getDefaultInstance();
      }

      public com.autodrive.message.Autodrive.SegmentList build() {
        com.autodrive.message.Autodrive.SegmentList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.autodrive.message.Autodrive.SegmentList buildPartial() {
        com.autodrive.message.Autodrive.SegmentList result = new com.autodrive.message.Autodrive.SegmentList(this);
        int from_bitField0_ = bitField0_;
        if (locationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            locations_ = java.util.Collections.unmodifiableList(locations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.locations_ = locations_;
        } else {
          result.locations_ = locationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.autodrive.message.Autodrive.SegmentList) {
          return mergeFrom((com.autodrive.message.Autodrive.SegmentList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.autodrive.message.Autodrive.SegmentList other) {
        if (other == com.autodrive.message.Autodrive.SegmentList.getDefaultInstance()) return this;
        if (locationsBuilder_ == null) {
          if (!other.locations_.isEmpty()) {
            if (locations_.isEmpty()) {
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLocationsIsMutable();
              locations_.addAll(other.locations_);
            }
            onChanged();
          }
        } else {
          if (!other.locations_.isEmpty()) {
            if (locationsBuilder_.isEmpty()) {
              locationsBuilder_.dispose();
              locationsBuilder_ = null;
              locations_ = other.locations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              locationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLocationsFieldBuilder() : null;
            } else {
              locationsBuilder_.addAllMessages(other.locations_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLocationsCount(); i++) {
          if (!getLocations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.autodrive.message.Autodrive.SegmentList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.autodrive.message.Autodrive.SegmentList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.autodrive.message.Autodrive.LocationMessage> locations_ =
        java.util.Collections.emptyList();
      private void ensureLocationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          locations_ = new java.util.ArrayList<com.autodrive.message.Autodrive.LocationMessage>(locations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.autodrive.message.Autodrive.LocationMessage, com.autodrive.message.Autodrive.LocationMessage.Builder, com.autodrive.message.Autodrive.LocationMessageOrBuilder> locationsBuilder_;

      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public java.util.List<com.autodrive.message.Autodrive.LocationMessage> getLocationsList() {
        if (locationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(locations_);
        } else {
          return locationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public int getLocationsCount() {
        if (locationsBuilder_ == null) {
          return locations_.size();
        } else {
          return locationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public com.autodrive.message.Autodrive.LocationMessage getLocations(int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);
        } else {
          return locationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder setLocations(
          int index, com.autodrive.message.Autodrive.LocationMessage value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.set(index, value);
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder setLocations(
          int index, com.autodrive.message.Autodrive.LocationMessage.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.set(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder addLocations(com.autodrive.message.Autodrive.LocationMessage value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder addLocations(
          int index, com.autodrive.message.Autodrive.LocationMessage value) {
        if (locationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLocationsIsMutable();
          locations_.add(index, value);
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder addLocations(
          com.autodrive.message.Autodrive.LocationMessage.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder addLocations(
          int index, com.autodrive.message.Autodrive.LocationMessage.Builder builderForValue) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.add(index, builderForValue.build());
          onChanged();
        } else {
          locationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder addAllLocations(
          java.lang.Iterable<? extends com.autodrive.message.Autodrive.LocationMessage> values) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, locations_);
          onChanged();
        } else {
          locationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder clearLocations() {
        if (locationsBuilder_ == null) {
          locations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          locationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public Builder removeLocations(int index) {
        if (locationsBuilder_ == null) {
          ensureLocationsIsMutable();
          locations_.remove(index);
          onChanged();
        } else {
          locationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public com.autodrive.message.Autodrive.LocationMessage.Builder getLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public com.autodrive.message.Autodrive.LocationMessageOrBuilder getLocationsOrBuilder(
          int index) {
        if (locationsBuilder_ == null) {
          return locations_.get(index);  } else {
          return locationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public java.util.List<? extends com.autodrive.message.Autodrive.LocationMessageOrBuilder> 
           getLocationsOrBuilderList() {
        if (locationsBuilder_ != null) {
          return locationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(locations_);
        }
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public com.autodrive.message.Autodrive.LocationMessage.Builder addLocationsBuilder() {
        return getLocationsFieldBuilder().addBuilder(
            com.autodrive.message.Autodrive.LocationMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public com.autodrive.message.Autodrive.LocationMessage.Builder addLocationsBuilder(
          int index) {
        return getLocationsFieldBuilder().addBuilder(
            index, com.autodrive.message.Autodrive.LocationMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.autodrive.message.LocationMessage locations = 1;</code>
       */
      public java.util.List<com.autodrive.message.Autodrive.LocationMessage.Builder> 
           getLocationsBuilderList() {
        return getLocationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.autodrive.message.Autodrive.LocationMessage, com.autodrive.message.Autodrive.LocationMessage.Builder, com.autodrive.message.Autodrive.LocationMessageOrBuilder> 
          getLocationsFieldBuilder() {
        if (locationsBuilder_ == null) {
          locationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.autodrive.message.Autodrive.LocationMessage, com.autodrive.message.Autodrive.LocationMessage.Builder, com.autodrive.message.Autodrive.LocationMessageOrBuilder>(
                  locations_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          locations_ = null;
        }
        return locationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.autodrive.message.SegmentList)
    }

    static {
      defaultInstance = new SegmentList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.autodrive.message.SegmentList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autodrive_message_LocationMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_autodrive_message_LocationMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_autodrive_message_SegmentList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_autodrive_message_SegmentList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017autodrive.proto\022\025com.autodrive.message" +
      "\"6\n\017LocationMessage\022\020\n\010latitude\030\001 \002(\001\022\021\n" +
      "\tlongitude\030\002 \002(\001\"H\n\013SegmentList\0229\n\tlocat" +
      "ions\030\001 \003(\0132&.com.autodrive.message.Locat" +
      "ionMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_autodrive_message_LocationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_autodrive_message_LocationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_autodrive_message_LocationMessage_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_com_autodrive_message_SegmentList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_autodrive_message_SegmentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_autodrive_message_SegmentList_descriptor,
        new java.lang.String[] { "Locations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
